version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install docker-compose==1.18.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker network create kafka-network
            docker-compose -f docker-compose.kafka.yml up -d
